version: '2.2'

services:

  myapp-mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    ports:
      - 3307:3306

  timesheet:
  
    image: samarrmdhn/devopsimage
    build: ./
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8082:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://myapp-mysql:3306/timesheet?autoReconnect=true&useSSL=false
