version: "3.9"
services:
  db:
    image: mysql:5.6
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: timesheet-spring
      MYSQL_USER: root
      MYSQL_PASSWORD: sab
      MYSQL_ROOT_HOST: '%' 
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8088:80
  timesheet:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/timesheet?autoReconnect=true&useSSL=false

    ports:
      - "3002:8082"
    image: samarrmdhn/devopsimage:${BUILD_NUMBER}
    depends_on:
      - db
      - phpmyadmin
volumes:
  dbdata:
